In [7]:
import numpy as np

# The NumPy `ndarray`: A Multidimensional Array Object

The `ndarray` (short for N-dimensional array) is the core data structure of the NumPy library, which is essential for numerical computing in Python. An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. The number of dimensions is the rank of the array, and the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [8]:
# Example-1(Batch Computations)
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.45782408, -1.46448315, -0.35461441],
       [ 0.50454426,  0.15965909, -0.11991823]])

The function `np.random.randn` in the NumPy library generates samples from the standard normal distribution, which is a normal (Gaussian) distribution with a mean of 0 and a standard deviation of 1. This function is often used in statistical simulations and for generating random data that follows a normal distribution.

In [9]:
# I then write mathematical operations with data:
data = data * 10
data

array([[ -4.57824076, -14.64483146,  -3.54614407],
       [  5.04544259,   1.59659088,  -1.19918226]])

In [10]:
data + data

array([[ -9.15648153, -29.28966292,  -7.09228813],
       [ 10.09088519,   3.19318176,  -2.39836451]])

 Every array has a shape, a tuple indicating the
 size of each dimension, and a dtype, an object describing the data type of the array:

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

## Creating ndarrays

The easiest way to create an array in NumPy is by using the `array` function. This function can take any sequence-like object, such as a list, and produce a new NumPy array containing the provided data. For example, a list can be easily converted into a NumPy array using this method.

In [13]:
list_array = [1, 2, 3, 4, 5]
arr = np.array(list_array)
arr

array([1, 2, 3, 4, 5])

Nested sequences, like a list of equal-length lists, will be converted into a multidimen
sional array:

In [15]:
nested_list = [[1, 2, 3],
              [4, 5, 6]]
nested_arr = np.array(nested_list)
nested_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
nested_arr.ndim # two dimentional arrary

2

In [17]:
nested_arr.shape

(2, 3)

As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
 given length or shape. empty creates an array without initializing its values to any par
ticular value. To create a higher dimensional array with these methods, pass a tuple
 for the shape:

In [20]:
zeros = np.zeros(6)
print(zeros)
n_zeros = np.zeros((2, 3))
print(n_zeros)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
ones = np.ones(6)
print(ones)
n_ones = np.ones((2, 3))
print(n_ones)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
np.empty((2, 3, 2))

array([[[1.24297816e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 6.82116729e-043]],

       [[5.27608251e-091, 2.46488551e+184],
        [2.36556713e+179, 1.32628559e-047],
        [6.48224659e+170, 4.93432906e+257]]])

 `np.arange` is an array-valued version of the built-in Python range function:

In [25]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

## Array creation functions
![Array creation functions](Assets/array_creation.png)

In [30]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])