In [1]:
import numpy as np

### Write a NumPy program to print the NumPy version on your system.

In [2]:
print(np.__version__)

1.24.3


### Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [3]:
lst = [12.23, 13.32, 100, 36.32]
print(np.array(lst))

[ 12.23  13.32 100.    36.32]


### Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [5]:
arr = np.arange(2, 11)
print(arr.reshape(3, 3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Write a NumPy program to create a null vector of size 10 and update the sixth value

In [10]:
null_vec = np.zeros(10)
null_vec[5] = 11
print(null_vec)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


### Write a NumPy program to create an array with values ranging from 12 to 38.

In [11]:
print(np.arange(12, 38))

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


### Write a NumPy program to reverse an array (the first element becomes the last)

In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]
