In [2]:
import numpy as np

# The NumPy `ndarray`: A Multidimensional Array Object

The `ndarray` (short for N-dimensional array) is the core data structure of the NumPy library, which is essential for numerical computing in Python. An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. The number of dimensions is the rank of the array, and the shape of an array is a tuple of integers giving the size of the array along each dimension.

## Creating ndarrays

The easiest way to create an array in NumPy is by using the `array` function. This function can take any sequence-like object, such as a list, and produce a new NumPy array containing the provided data. For example, a list can be easily converted into a NumPy array using this method.

In [3]:
list_array = [1, 2, 3, 4, 5]
arr = np.array(list_array)
arr

array([1, 2, 3, 4, 5])

Nested sequences, like a list of equal-length lists, will be converted into a multidimen
sional array:

In [4]:
nested_list = [[1, 2, 3],
              [4, 5, 6]]
nested_arr = np.array(nested_list)
nested_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
nested_arr.ndim # two dimentional arrary

2

In [6]:
nested_arr.shape

(2, 3)

As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
 given length or shape. empty creates an array without initializing its values to any par
ticular value. To create a higher dimensional array with these methods, pass a tuple
 for the shape:

In [7]:
zeros = np.zeros(6)
print(zeros)
n_zeros = np.zeros((2, 3))
print(n_zeros)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
ones = np.ones(6)
print(ones)
n_ones = np.ones((2, 3))
print(n_ones)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
np.empty((2, 3, 2))

array([[[6.23042070e-307, 7.56587584e-307],
        [1.37961302e-306, 6.23053614e-307],
        [6.23053954e-307, 9.34609790e-307]],

       [[8.45593934e-307, 9.34600963e-307],
        [1.86921143e-306, 6.23061763e-307],
        [2.22522053e-306, 1.11261095e-306]]])

 `np.arange` is an array-valued version of the built-in Python range function:

In [10]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

## Array creation functions
![Array creation functions](Assets/array_creation.png)

In [11]:
np.eye(3, 3) #np.eye(N, M=None, k=0, dtype=float, order='C')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.identity(3) # np.identity(n, dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Data Types for ndarrays
The data type or dtype is a special object containing the information (or metadata,
 data about data) the ndarray needs to interpret a chunk of memory as a particular
 type of data:

In [13]:
# Ex
int_arr = np.array([1, 2, 3], dtype=np.int32)
int_arr

array([1, 2, 3])

In [14]:
int_arr.dtype

dtype('int32')

In [15]:
float_arr = np.array([2, 5, 1], dtype = np.float64)
float_arr

array([2., 5., 1.])

In [16]:
float_arr.dtype

dtype('float64')

## NumPy data types

![Data Types](Assets/data_types.png)


You can explicitly convert or cast an array from one dtype to another using ndarray’s
 astype method:
 Calling astype always creates a new array (a copy of the data), even
 if the new dtype is the same as the old dtype.

In [17]:
int_arr = np.array([1, 2, 3], dtype = np.int32)

In [41]:
int_arr.dtype

dtype('int32')

In [42]:
float_arr = int_arr.astype(np.float64)

In [18]:
float_arr.dtype

dtype('float64')

In [19]:
 numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [20]:
float_arr = numeric_strings.astype(float)

In [21]:
float_arr

array([ 1.25, -9.6 , 42.  ])

In [23]:
int_array = np.arange(10)

In [24]:
target_dtype = np.array([1.2, 2.3], dtype = np.float64)
int_array.astype(target_dtype.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Arithmetic with NumPy Arrays
Arrays are important because they enable you to express batch operations on data
 without writing any for loops. NumPy users call this vectorization. Any arithmetic
 operations between equal-size arrays applies the operation element-wise:

In [25]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [27]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparisons between arrays of the same size yield boolean arrays:

In [30]:
arr_2 = np.array([
    [7, 8, 1],
    [2, 9, 0]
])

In [31]:
arr_2 > arr

array([[ True,  True, False],
       [False,  True, False]])

## Basic Indexing and Slicing

In [60]:
arr = np.arange(10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[-1]

9

In [63]:
arr[4]

4

In [64]:
arr[3:6]

array([3, 4, 5])

In [65]:
arr[2:5] = 0

In [66]:
arr

array([0, 1, 0, 0, 0, 5, 6, 7, 8, 9])

Python’s built-in lists is that array slices are views on the original array.
 This means that the data is not copied, and any modifications to the view will be
 reflected in the source array.

In [74]:
# Example
arr_slice = arr[2:6]
arr_slice[1] = -100

In [75]:
arr

array([   0,    1,    0, -100, -100, -100,    6, -100,    8,    9])

The “bare” slice [:] will assign to all values in an array:

In [76]:
arr_slice[:] = 20

In [77]:
arr_slice

array([20, 20, 20, 20])

In [78]:
arr

array([   0,    1,   20,   20,   20,   20,    6, -100,    8,    9])

In [79]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [80]:
arr_2d[2]

array([7, 8, 9])

In [81]:
arr_2d[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [82]:
arr_2d[1][2]

6

axis 0 as the “rows” of the array and axis 1 as the “columns.”

![2d slicing](Assets/2d_array_slicing.png)


In [84]:
arr_3d = np.array([
    [[1, 2, 3], 
    [4, 5, 6]], 
    
    [[7, 8, 9], 
     [10, 11, 12]]
])

In [85]:
arr_3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [86]:
arr_3d[1, 1]

array([10, 11, 12])

In [87]:
arr_3d[1, 1, 0]

10

In [90]:
arr_3d[:, 0:1, 1:]

array([[[2, 3]],

       [[8, 9]]])

## Indexing with slices

In [92]:
array = np.arange(1, 10).reshape(3, 3)

In [93]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
array[:2, 1:]

array([[2, 3],
       [5, 6]])

In [97]:
array[1, :2]

array([4, 5])

In [99]:
array[:2, 2]

array([3, 6])

Note that a colon by itself means to take the entire
 axis, so you can slice only higher dimensional axes by doing:

In [102]:
array[:, :1]

array([[1],
       [4],
       [7]])

In [103]:
array[1:, 1:] = 0

In [104]:
array

array([[1, 2, 3],
       [4, 0, 0],
       [7, 0, 0]])

![2d array slicing](Assets/2d_slicing.png)

## Boolean Indexing

In [2]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [3]:
data = np.random.randn(7, 4)

In [4]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [5]:
data

array([[-0.95954772,  0.29020755,  0.07721473, -0.33778974],
       [-0.75925294, -1.62382342, -0.03504342, -0.69459692],
       [-1.6699623 , -0.94827081,  1.02196233, -0.46235455],
       [ 2.01197207, -0.16963898,  0.02570721,  1.62517808],
       [ 1.01725767,  0.69185359,  0.40033476,  0.87511716],
       [-0.32617058,  1.29271528, -0.48660428, -0.65431932],
       [-0.20523852, -0.44527071,  0.89789274, -0.4845306 ]])

In [6]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [7]:
data[names == 'Bob']

array([[-0.95954772,  0.29020755,  0.07721473, -0.33778974],
       [ 2.01197207, -0.16963898,  0.02570721,  1.62517808]])

In [8]:
data[names == 'Will', 2:]

array([[ 1.02196233, -0.46235455],
       [ 0.40033476,  0.87511716]])

In [9]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [10]:
data[~(names == 'Bob')]

array([[-0.75925294, -1.62382342, -0.03504342, -0.69459692],
       [-1.6699623 , -0.94827081,  1.02196233, -0.46235455],
       [ 1.01725767,  0.69185359,  0.40033476,  0.87511716],
       [-0.32617058,  1.29271528, -0.48660428, -0.65431932],
       [-0.20523852, -0.44527071,  0.89789274, -0.4845306 ]])

The ~ operator can be useful when you want to invert a general condition:

In [14]:
condition = names == 'Bob'

In [15]:
data[~condition]

array([-0.32617058,  1.29271528, -0.48660428, -0.65431932])

The Python keywords and and or do not work with boolean arrays.
 Use & (and) and | (or) instead.

In [16]:
mask = (names == 'Bob') | (names == 'Will')

In [17]:
mask

True

In [18]:
data[mask]

array([[[-0.95954772,  0.29020755,  0.07721473, -0.33778974],
        [-0.75925294, -1.62382342, -0.03504342, -0.69459692],
        [-1.6699623 , -0.94827081,  1.02196233, -0.46235455],
        [ 2.01197207, -0.16963898,  0.02570721,  1.62517808],
        [ 1.01725767,  0.69185359,  0.40033476,  0.87511716],
        [-0.32617058,  1.29271528, -0.48660428, -0.65431932],
        [-0.20523852, -0.44527071,  0.89789274, -0.4845306 ]]])

In [19]:
data[data<0] = 0

In [20]:
data

array([[0.        , 0.29020755, 0.07721473, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.02196233, 0.        ],
       [2.01197207, 0.        , 0.02570721, 1.62517808],
       [1.01725767, 0.69185359, 0.40033476, 0.87511716],
       [0.        , 1.29271528, 0.        , 0.        ],
       [0.        , 0.        , 0.89789274, 0.        ]])

In [25]:
data[names != 'Will'] = 7
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

## Fancy Indexing
 Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [27]:
arr = np.empty((8, 4))

In [28]:
for i in range(8):
    arr[i] = i

In [29]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [30]:
arr[[1, 2, 3]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [33]:
arr[[1]]

array([[1., 1., 1., 1.]])

In [34]:
arr[[-3, -4]]

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.]])

## Transposing Arrays and Swapping Axes
Transposing is a special form of reshaping that similarly returns a view on the under
lying data without copying anything. Arrays have the transpose method and also the 
special T attribute:

In [36]:
arr = np.arange(15).reshape((3, 5))

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [39]:
arr = np.random.randn(6, 3)

In [45]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [41]:
np.dot(arr.T, arr)

array([[ 1.37823652,  0.94775491,  1.09076707],
       [ 0.94775491, 16.17619355,  1.69553615],
       [ 1.09076707,  1.69553615,  2.16842927]])

In [47]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

For higher dimensional arrays, transpose will accept a tuple of axis numbers to per
mute the axes (for extra mind bending):
Here, arr has the shape (2, 2, 4), where:

- 2 is the size of the first dimension (axis 0)
- 2 is the size of the second dimension (axis 1)
- 4 is the size of the third dimension (axis 2)
Understanding arr.transpose((1, 0, 2))
The argument (1, 0, 2) specifies the order of the dimensions after transposition. The numbers in the tuple represent the original positions of the axes in the new order.

- 1 means the first axis in the transposed array will be the second axis of the original array.
- 0 means the second axis in the transposed array will be the first axis of the original array.
- 2 means the third axis in the transposed array will be the same as the third axis of the original array.
Thus, applying arr.transpose((1, 0, 2)) to arr will rearrange the dimensions from (2, 2, 4) to (2, 2, 4).

In [42]:
arr = np.arange(16).reshape((2, 2, 4))

In [43]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [51]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])