In [7]:
import numpy as np

# The NumPy `ndarray`: A Multidimensional Array Object

The `ndarray` (short for N-dimensional array) is the core data structure of the NumPy library, which is essential for numerical computing in Python. An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. The number of dimensions is the rank of the array, and the shape of an array is a tuple of integers giving the size of the array along each dimension.

## Creating ndarrays

The easiest way to create an array in NumPy is by using the `array` function. This function can take any sequence-like object, such as a list, and produce a new NumPy array containing the provided data. For example, a list can be easily converted into a NumPy array using this method.

In [13]:
list_array = [1, 2, 3, 4, 5]
arr = np.array(list_array)
arr

array([1, 2, 3, 4, 5])

Nested sequences, like a list of equal-length lists, will be converted into a multidimen
sional array:

In [15]:
nested_list = [[1, 2, 3],
              [4, 5, 6]]
nested_arr = np.array(nested_list)
nested_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
nested_arr.ndim # two dimentional arrary

2

In [17]:
nested_arr.shape

(2, 3)

As examples, zeros and ones create arrays of 0s or 1s, respectively, with a
 given length or shape. empty creates an array without initializing its values to any par
ticular value. To create a higher dimensional array with these methods, pass a tuple
 for the shape:

In [20]:
zeros = np.zeros(6)
print(zeros)
n_zeros = np.zeros((2, 3))
print(n_zeros)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
ones = np.ones(6)
print(ones)
n_ones = np.ones((2, 3))
print(n_ones)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
np.empty((2, 3, 2))

array([[[1.24297816e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 6.82116729e-043]],

       [[5.27608251e-091, 2.46488551e+184],
        [2.36556713e+179, 1.32628559e-047],
        [6.48224659e+170, 4.93432906e+257]]])

 `np.arange` is an array-valued version of the built-in Python range function:

In [25]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

## Array creation functions
![Array creation functions](Assets/array_creation.png)

In [31]:
np.eye(3, 3) #np.eye(N, M=None, k=0, dtype=float, order='C')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.identity(3) # np.identity(n, dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Data Types for ndarrays
The data type or dtype is a special object containing the information (or metadata,
 data about data) the ndarray needs to interpret a chunk of memory as a particular
 type of data:

In [37]:
# Ex
int_arr = np.array([1, 2, 3], dtype=np.int32)
int_arr

array([1, 2, 3])

In [35]:
int_arr.dtype

dtype('int32')

In [38]:
float_arr = np.array([2, 5, 1], dtype = np.float64)
float_arr

array([2., 5., 1.])

In [39]:
float_arr.dtype

dtype('float64')

## NumPy data types

![Data Types](Assets/data_types.png)


You can explicitly convert or cast an array from one dtype to another using ndarray’s
 astype method:
 Calling astype always creates a new array (a copy of the data), even
 if the new dtype is the same as the old dtype.

In [40]:
int_arr = np.array([1, 2, 3], dtype = np.int32)

In [41]:
int_arr.dtype

dtype('int32')

In [42]:
float_arr = int_arr.astype(np.float64)

In [43]:
float_arr.dtype

dtype('float64')

In [44]:
 numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [49]:
float_arr = numeric_strings.astype(float)

In [50]:
float_arr

array([ 1.25, -9.6 , 42.  ])

In [51]:
int_array = np.arange(10)

In [52]:
target_dtype = np.array([1.2, 2.3], dtype = np.float64)
int_array.astype(target_dtype.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Arithmetic with NumPy Arrays
Arrays are important because they enable you to express batch operations on data
 without writing any for loops. NumPy users call this vectorization. Any arithmetic
 operations between equal-size arrays applies the operation element-wise:

In [53]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [54]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [55]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [56]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [57]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparisons between arrays of the same size yield boolean arrays:

In [58]:
arr_2 = np.array([
    [7, 8, 1],
    [2, 9, 0]
])

In [59]:
arr_2 > arr

array([[ True,  True, False],
       [False,  True, False]])

## Basic Indexing and Slicing

In [60]:
arr = np.arange(10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[-1]

9

In [63]:
arr[4]

4

In [64]:
arr[3:6]

array([3, 4, 5])

In [65]:
arr[2:5] = 0

In [66]:
arr

array([0, 1, 0, 0, 0, 5, 6, 7, 8, 9])

Python’s built-in lists is that array slices are views on the original array.
 This means that the data is not copied, and any modifications to the view will be
 reflected in the source array.

In [74]:
# Example
arr_slice = arr[2:6]
arr_slice[1] = -100

In [75]:
arr

array([   0,    1,    0, -100, -100, -100,    6, -100,    8,    9])

The “bare” slice [:] will assign to all values in an array:

In [76]:
arr_slice[:] = 20

In [77]:
arr_slice

array([20, 20, 20, 20])

In [78]:
arr

array([   0,    1,   20,   20,   20,   20,    6, -100,    8,    9])

In [79]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [80]:
arr_2d[2]

array([7, 8, 9])

In [81]:
arr_2d[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [82]:
arr_2d[1][2]

6

axis 0 as the “rows” of the array and axis 1 as the “columns.”

![2d slicing](Assets/2d_array_slicing.png)


In [84]:
arr_3d = np.array([
    [[1, 2, 3], 
    [4, 5, 6]], 
    
    [[7, 8, 9], 
     [10, 11, 12]]
])

In [85]:
arr_3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [86]:
arr_3d[1, 1]

array([10, 11, 12])

In [87]:
arr_3d[1, 1, 0]

10

In [90]:
arr_3d[:, 0:1, 1:]

array([[[2, 3]],

       [[8, 9]]])