In [1]:
import numpy as np

In [2]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [4]:
for i in c.flat:
    print(i)

0
1
2
10
12
13
100
101
102
110
112
113


In [7]:
c.reshape(-1, 1)

array([[  0],
       [  1],
       [  2],
       [ 10],
       [ 12],
       [ 13],
       [100],
       [101],
       [102],
       [110],
       [112],
       [113]])

In [12]:
c[:, np.newaxis].shape

(2, 1, 2, 3)

In [13]:
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 0],  # each value corresponds to a color in the palette
                  [0, 3, 4, 0]])
palette[image]  # the (2, 4, 3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [20]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0, 4.0])
b = b[:, np.newaxis]
print(b.shape)
a + b

(4, 1)


array([[ 1.,  1.,  1.],
       [12., 12., 12.],
       [23., 23., 23.],
       [34., 34., 34.]])