## Universal Functions
 A universal function, or ufunc, is a function that performs element-wise operations
 on data in ndarrays.

In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
x = np.random.randn(6)
y = np.random.randn(6)

Here, numpy.maximum computed the element-wise maximum of the elements in x and
 y.

In [7]:
np.maximum(x, y)

array([-1.00901011,  0.40449845,  1.39314488, -0.03123504,  0.02210446,
        0.86290083])

 modf is one example, a vec
torized version of the built-in Python divmod; it returns the fractional and integral
 parts of a floating-point array:

In [13]:
arr = np.random.randn(7)*4
arr

array([-1.45299277, -2.62889642,  3.9847427 , -2.54534147, -0.4726906 ,
        8.19514171, -5.33352629])

In [14]:
reminder, whole_part = np.modf(arr)

In [15]:
reminder

array([-0.45299277, -0.62889642,  0.9847427 , -0.54534147, -0.4726906 ,
        0.19514171, -0.33352629])

In [16]:
whole_part

array([-1., -2.,  3., -2., -0.,  8., -5.])

### Ufuncs
![Ufuncs](Assets/ufunc.png)

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.add(a, b)
print(result) 

[5 7 9]


In [18]:
result = np.subtract(a, b)
print(result)

[-3 -3 -3]


In [19]:
result = np.multiply(a, b)
print(result)

[ 4 10 18]


In [20]:
angles = np.array([0, np.pi / 2, np.pi])
result = np.sin(angles)
print(result)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Binary universal functions
![Bin](Assets/bin_1.png)
![Bin](Assets/bin_2.png)