## Universal Functions
 A universal function, or ufunc, is a function that performs element-wise operations
 on data in ndarrays.

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
x = np.random.randn(6)
y = np.random.randn(6)

Here, numpy.maximum computed the element-wise maximum of the elements in x and
 y.

In [6]:
np.maximum(x, y)

array([0.70471803, 1.72530091, 0.16225562, 0.93902531, 0.45485075,
       1.35208327])

 modf is one example, a vec
torized version of the built-in Python divmod; it returns the fractional and integral
 parts of a floating-point array:

In [7]:
arr = np.random.randn(7)*4
arr

array([-1.47444101,  2.32195106,  4.86167004,  3.75945476, -2.11529395,
       -6.28735339, -5.33073862])

In [8]:
reminder, whole_part = np.modf(arr)

In [9]:
reminder

array([-0.47444101,  0.32195106,  0.86167004,  0.75945476, -0.11529395,
       -0.28735339, -0.33073862])

In [10]:
whole_part

array([-1.,  2.,  4.,  3., -2., -6., -5.])

### Ufuncs
![Ufuncs](Assets/ufunc.png)

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.add(a, b)
print(result) 

[5 7 9]


In [12]:
result = np.subtract(a, b)
print(result)

[-3 -3 -3]


In [13]:
result = np.multiply(a, b)
print(result)

[ 4 10 18]


In [14]:
angles = np.array([0, np.pi / 2, np.pi])
result = np.sin(angles)
print(result)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Binary universal functions
![Bin](Assets/bin_1.png)
![Bin](Assets/bin_2.png)